---
abstract: 'Pack an application into a single runable file'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Implode
no_index:
  directory:
    - t
    - inc
requires:
  Carton: 1.0
  perl: 5.010001
resources:
  bugtracker: https://github.com/jhthorsen/app-implode/issues
  homepage: https://github.com/jhthorsen/app-implode
  repository: https://github.com/jhthorsen/app-implode.git
version: 0.03
